### PR TITLE
Add TypeScript types declaration file (resolve #2)

### LINKED ISSUE #2: TypeScript types declaration file
Hey, I saw this package from Reddit. 😄 It could use a types declaration file so that TypeScript developers can utilise TS while using this. If you'd like I can write a file for you.

### PR DESCRIPTION
**Pull request by geopic**
Here is the file for TS developers. :fireworks: 

...So code written in TypeScript using this library needs to be written a little differently than in the code sample currently in the 'Usage' section of the Readme:

```ts
// Using 'require' loses all type information, making TS redundant
import StormDB from 'stormdb';

// This is the JavaScript approach depicted in the Readme
const engine = new StormDB.localFileEngine("./db.stormdb");
const db = StormDB(engine);

// And here is the TypeScript approach, necessary because 'engine' throws an error
// that says "Only a void function can be called with the 'new' keyword [ts(2350)]",
// while 'db' throws an error that the StormDB class needs to be invoked (called with 'new').
const engine = StormDB.localFileEngine('./db.stormdb');
const db = new StormDB(engine);
```

I've had to hack on it a little bit since TypeScript doesn't accept the default export *and* non-default additional export in `index.js` (it either should be one single default exports or multiple non-default exports). `localFileEngine` is declared as a static method in the `StormDB` class, which returns the *class* of `LocalFileEngine` with its respective methods. 

I hope the hacky approach is ok. If you have any queries, let me know.

### CODE REVIEW

**Comment by TomPrograms** [comment]
As soon as you give the go ahead, we can get this merged! Thanks again for your contribution!

**Comment by geopic** [comment]
Go ahead and merge it @TomPrograms :+1:

**Comment by geopic** [comment]
Actually, before you do, I will amend `map()`, `filter()` and `sort()` super-quick to avoid using `any`.

**Comment by TomPrograms** [comment]
Alright thanks a lot for your work.

**Comment by geopic** [comment]
No problem, anytime :smile:

**Pull request merged**
